name: Generate blog posts

on:
  push:
    branches:
      - main

jobs:
  generate_readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tools/requirements.txt

    - name: Run script
      run: python tools/generate_blog_posts.py

    # push the changes to the gh-pages branch
      # git push remote blog:gh-pages
    # change git add to only add articles and not templates, or md versions
    # only add .html files, remove template
    - name: Commit and push changes
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add blog/articles/*.html
        git restore --staged template.html
        git commit -m "AUTO: create blog posts" || exit 0  # Exit gracefully if no changes to commit
        git push remote blog:gh-pages
