name: Generate blog posts

on:
  push:
    paths:
    - 'tools/blog/articles/**'

jobs:
  generate_readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: gh-pages

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tools/requirements.txt

    - name: Run script
      run: python tools/blog/generate_blog_posts.py

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        title: "[AUTO] Merge generated blog posts"
        commit-message: "AUTO: Create blog posts from template"
        add-paths: blog/*.html
        branch: create-blog-posts
        assignees: cartwatson
